version: '3.8'

services:
  postgres-db:
    image: postgres:15
    container_name: postgres-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - madrid_net

volumes:
  postgres_data:

networks:
  madrid_net:
    driver: bridge



# "Run a PostgreSQL container using the official image, set credentials,
# expose it on port 5432, and save the data in a volume so it persists."